---
# This is template of playbook
- name: Ansible playbook
  hosts: localhost
  vars:
    aptcachetime: 3600
    user: "{{ lookup('env','USER') }}"
    home: "{{ lookup('env','HOME') }}"
  become: true
  become_method: sudo
  become_user: "{{ user }}"
  roles:
    # Run playbook.sh in the scripts and roles will be completed automatically to playbook.yml.
    # Use command: cd scripts && bash playbook.sh && cd ..
