---

- name: Ansible playbook
  hosts: localhost
  become: false
  become_method: sudo
  vars:
    cache_valid_time: 3600
    user: "{{ lookup('env','USER') }}"
    home: "{{ lookup('env','HOME') }}"
  roles:
    # - git
     - desktop-cleanup
