---

- name: Update APT cache
  sudo: yes
  apt: update_cache=yes cache_valid_time={{ aptcachetime }}

- name: Install require dependencies
  sudo: yes
  apt: "pkg={{ item }} state=present"
  with_items:
    - build-essential
    - automake
    - libtool
    - git

- name: Clone libsass repository
  sudo: yes
  git:
    repo: https://github.com/sass/libsass.git
    dest: "{{ sass.libsass_path }}"
    version: "{{ sass.libssas_version }}"
    force: yes
    depth: 1
    update: yes
    accept_hostkey: yes
  tags:
    - git
    - libsass

- name: Clone saasc repository
  sudo: yes
  git:
    repo: https://github.com/sass/sassc.git
    dest: "{{ sass.sassc_path }}"
    version: "{{ sass.sassc_version }}"
    force: yes
    depth: 1
    update: yes
    accept_hostkey: yes
  tags:
    - git
    - sassc

- name: Create configure script libsass
  sudo: yes
  shell: "autoreconf {{ sass.libsass_path }} --force --install"
  tags:
    - autoreconf
    - libsass

- name: Build the library libsass
  sudo: yes
  shell: "make -C {{ sass.libsass_path }}"
  environment:
    SASS_LIBSASS_PATH: "{{ sass.libsass_path }}"
  tags:
    - make
    - libsass

- name: Install the library libsass
  sudo: yes
  shell: "make -C {{ sass.libsass_path }} install"
  environment:
    SASS_LIBSASS_PATH: "{{ sass.libsass_path }}"
  tags:
    - make
    - install
    - libsass

- name: Create configure script sassc
  sudo: yes
  shell: "autoreconf {{ sass.sassc_path }} --force --install"
  tags:
    - autoreconf
    - sassc

- name: Build the library sassc
  sudo: yes
  shell: "make -C {{ sass.sassc_path }}"
  environment:
    SASS_LIBSASS_PATH: "{{ sass.libsass_path }}"
  tags:
    - make
    - sassc

- name: Create symbolic link to sassc
  sudo: yes
  file:
    src: "{{ sass.sassc_path }}/bin/sassc"
    dest: "/usr/bin/sassc"
    state: link
  tags:
    - symlinks
    - sassc
