---

- name: Install ZSH with Aptitude
  apt: pkg=zsh state=latest update_cache=yes cache_valid_time={{ cache_valid_time }}

- name: Make ZSH default shell
  user: name="{{ user }}" shell=/bin/zsh

- name: Create OhMyZsh repository folder
  file:
    path: "{{ user }}/.dotfiles"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
  when: zsh.oh_my_zsh.install

- name: Clone OhMyZsh repository
  git: repo=git://github.com/robbyrussell/oh-my-zsh.git dest="{{ home }}/.oh-my-zsh"
  when: zsh.oh_my_zsh.install

- name: Install OhMyZsh
  script: "{{ home }}/.oh-my-zsh/tools/install.sh"
  when: zsh.oh_my_zsh.install

- name: Create a new zsh configuration file
  copy:
    src: "{{ home }}/.oh-my-zsh/templates/zshrc.zsh-template"
    dest: "{{ home }}/.zshrc"
    owner: "{{ user }}"
    group: "{{ user }}"
  when: zsh.oh_my_zsh.install

- name: Set theme
  lineinfile:
    path: "{{ home }}/.zshrc"
    regexp: '^ZSH_THEME='
    line: 'ZSH_THEME="{{ zsh.oh_my_zsh.theme }}"'
  when: zsh.oh_my_zsh.install

- name: Set plugins
  lineinfile:
    path: "{{ home }}/.zshrc"
    regexp: '^plugins='
    line: 'plugins=({{ zsh.oh_my_zsh.plugins }})'
  when: zsh.oh_my_zsh.install
