---

- name: Set php_executable variable to a default if not defined.
  set_fact:
    php_executable: php
  when: php_executable is not defined

- name: Check if Composer is installed.
  stat: "path={{ composer.path }}"
  register: composer_bin

- name: Download Composer installer.
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: 0755
  when: not composer_bin.stat.exists

- name: Run Composer installer.
  command: >
    {{ php_executable }} composer-installer.php {% if composer.version != '' %} --version={{ composer.version }}{% endif %}
    chdir=/tmp
  when: not composer_bin.stat.exists

- name: Move Composer into globally-accessible location.
  shell: >
    mv /tmp/composer.phar {{ composer.path }}
    creates={{ composer.path }}
  when: not composer_bin.stat.exists

- name: Update Composer to latest version (if configured).
  shell: >
    {{ php_executable }} {{ composer.path }} self-update
  register: composer_update
  changed_when: "'Updating to version' in composer_update.stdout"
  when: composer.keep_updated

- name: Ensure composer directory exists.
  file:
    path: "{{ composer.home_path }}"
    owner: "{{ composer.home_owner }}"
    group: "{{ composer.home_group }}"
    state: directory

- name: compile sources
    environment:
      PATH: "{{ lookup('env', 'PATH') }}:{{ lookup('env', 'HOME') }}/.composer/vendor/bin"


- name: Add GitHub OAuth token for Composer (if configured).
  become: yes
  become_user: "{{ composer.home_owner }}"
  template:
    src: "auth.json.j2"
    dest: "{{ composer.home_path }}/auth.json"
    owner: "{{ composer.home_owner }}"
    group: "{{ composer.home_group }}"
  when: composer.github_oauth_token != ''

- include: global-require.yml
  when: composer.global_packages|length > 0

- include: project-bin.yml
  when: composer.add_project_to_path
