---

- name: Install git and git-svn
  apt: pkg=git,git-svn state=latest update_cache=yes cache_valid_time={{ cache_valid_time }}
  become: true

- name: Set user.email
  git_config:
    name: user.email
    scope: global
    value: "{{ git.user_email }}"

- name: Set user.name
  git_config:
    name: user.name
    scope: global
    value: "{{ git.user_name }}"

- name: Set core.editor
  git_config:
    name: core.editor
    scope: global
    value: "{{ git.core_editor }}"

