---

- name: Add Atom repository (Webupd8team) (add-apt-repository ppa:webupd8team/atom)
  apt_repository: repo="ppa:webupd8team/atom" state=present

- name: Install Atom text editor
  apt: name=atom state=latest cache_valid_time=0
  become: true
  become_user: root

- name: Setup Atom Packages
  apm: name=sync-settings # All others packages are managed by sync-settings
  become: true
  become_user: "{{ user }}"
