---

- name: Install Default OpenJDK
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time={{ cache_valid_time }}
  with_items:
    - default-jdk
    - default-jre-headless
  become: true
