---

- name: Configure the Oracle APT key
  apt_key: url=https://www.virtualbox.org/download/oracle_vbox.asc state=present
  become: true

- name: Configure the VirtualBox APT repositories
  apt_repository: repo="deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib" state=present
  become: true

- name: Install VirtualBox
  apt: name={{ item }} state=latest update_cache=yes cache_valid_time=0
  with_items:
    - virtualbox
    - virtualbox-dkms
  become: true
