---

- name: Configure the Oracle APT key
  apt_key: url=http://download.virtualbox.org/virtualbox/debian/oracle_vbox_2016.asc state=present

- name: Configure the VirtualBox APT repositories
  apt_repository: repo="deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib" state=present

- name: Install VirtualBox
  apt: name={{ item }} state=latest update_cache=yes cache_valid_time=0
  with_items:
    - "virtualbox-{{ virtualbox.version }}"
    - virtualbox-dkms
