---

- name: Add Haguichi repository (Webupd8team)
  apt_repository: repo="ppa:webupd8team/haguichi" state=present

- name: Install Haguichi
  apt: name=haguichi state=latest cache_valid_time=0

- name: Install Hamachi
  apt: deb="{{ haguichi.hamachi_package_url }}"
