---

# Reassign path :
# xdg-user-dirs-update --set NAME ABSOLUTE_PATH
#
# Available values for NAME
#   DESKTOP
#   DOWNLOAD
#   TEMPLATES
#   PUBLICSHARE
#   DOCUMENTS
#   MUSIC
#   PICTURES
#   VIDEOS

- name: Create XDG directories
  file: path="{{ home }}/{{ item }}" force=no state=directory mode=0755 owner={{ user }} group={{ user }}
  with_items:
    - Desktop
    - Downloads
    - Templates
    - Public
    - Documents
    - Music
    - Pictures
    - Videos

- stat: path={{ home }}/{{ item.path }}
  register: "{{ item.dest }}"
  with_items:
    - { path: '{{ desktop.cleanup.xdg_directories.xdg_desktop }}', dest: 'Desktop' }
    - { path: '{{ desktop.cleanup.xdg_directories.xdg_downloads }}', dest: 'Downloads' }
    - { path: '{{ desktop.cleanup.xdg_directories.xdg_templates }}', dest: 'Templates' }
    - { path: '{{ desktop.cleanup.xdg_directories.xdg_public }}', dest: 'Public' }
    - { path: '{{ desktop.cleanup.xdg_directories.xdg_documents }}', dest: 'Documents' }
    - { path: '{{ desktop.cleanup.xdg_directories.xdg_music }}', dest: 'Music' }
    - { path: '{{ desktop.cleanup.xdg_directories.xdg_pictures }}', dest: 'Pictures' }
    - { path: '{{ desktop.cleanup.xdg_directories.xdg_videos }}', dest: 'Videos' }

- name: Copy content of old XDG directories to new
  copy: src={{ home }}/{{ item.src }}/ dest={{ home }}/{{ item.dest }} owner={{ user }} group={{ user }}
  ignore_errors: true
  when: "{{ item.dest }}.stat.exists == 1"
  with_items:
    - { src: '{{ desktop.cleanup.xdg_directories.xdg_desktop }}', dest: 'Desktop' }
    - { src: '{{ desktop.cleanup.xdg_directories.xdg_downloads }}', dest: 'Downloads' }
    - { src: '{{ desktop.cleanup.xdg_directories.xdg_templates }}', dest: 'Templates' }
    - { src: '{{ desktop.cleanup.xdg_directories.xdg_public }}', dest: 'Public' }
    - { src: '{{ desktop.cleanup.xdg_directories.xdg_documents }}', dest: 'Documents' }
    - { src: '{{ desktop.cleanup.xdg_directories.xdg_music }}', dest: 'Music' }
    - { src: '{{ desktop.cleanup.xdg_directories.xdg_pictures }}', dest: 'Pictures' }
    - { src: '{{ desktop.cleanup.xdg_directories.xdg_videos }}', dest: 'Videos' }

- name: Remove old XDG directories
  file: path="{{ home }}/{{ item }}" force=yes state=absent
  with_items:
    - "{{ desktop.cleanup.xdg_directories.xdg_desktop }}"
    - "{{ desktop.cleanup.xdg_directories.xdg_downloads }}"
    - "{{ desktop.cleanup.xdg_directories.xdg_templates }}"
    - "{{ desktop.cleanup.xdg_directories.xdg_public }}"
    - "{{ desktop.cleanup.xdg_directories.xdg_documents }}"
    - "{{ desktop.cleanup.xdg_directories.xdg_music }}"
    - "{{ desktop.cleanup.xdg_directories.xdg_pictures }}"
    - "{{ desktop.cleanup.xdg_directories.xdg_videos }}"

- name: Update user-dirs.dirs (config file)
  copy: src="user-dirs.dirs" dest="{{ home }}/.config/user-dirs.dirs" force=yes

- name : Run xdg-user-dirs-update
  shell: xdg-user-dirs-update
