---
# See https://github.com/adapta-project/adapta-gtk-theme
# Clean theme with:
#          sudo rm -rf /usr/share/themes/{Adapta,Adapta-Eta,Adapta-Nokto,Adapta-Nokto-Eta}
#          rm -rf ~/.local/share/themes/{Adapta,Adapta-Eta,Adapta-Nokto,Adapta-Nokto-Eta}
#          rm -rf ~/.themes/{Adapta,Adapta-Eta,Adapta-Nokto,Adapta-Nokto-Eta}

- name: Install Required Components (without libsass and sassc)
  apt: pkg={{ item }} state=latest cache_valid_time={{ aptcachetime }}
  with_items:
    - autoconf
    - automake
    - inkscape
    - libgdk-pixbuf2.0-dev
    - libglib2.0-dev
    - librsvg2-dev
    - libsass0
    - libxml2-utils
    - pkg-config
    - gnome-shell
    - parallel

- name: Install libsass and sassc
  include_role:
    name: sass
  tags: ['sassc', 'libsass']

- name: Install adapta-gtk-theme
  git: repo=https://github.com/adapta-project/adapta-gtk-theme.git dest="{{ ansible_env.HOME }}/.cache/adapta-gtk-theme" update=yes accept_hostkey=yes
  register: adapta_gtk_theme_git
  become: true
  become_user: "{{ ansible_env.USER }}"

- name: Configure
  command: ./autogen.sh --enable-parallel --enable-chrome --enable-plank
  args:
    chdir: "{{ ansible_env.HOME }}/.cache/adapta-gtk-theme"
  register: adapta_gtk_theme_configure
  become: true
  become_user: "{{ ansible_env.USER }}"
  when: adapta_gtk_theme_git.changed

- name: Make
  command: make
  args:
    chdir: "{{ ansible_env.HOME }}/.cache/adapta-gtk-theme"
  register: adapta_theme_make
  when: adapta_gtk_theme_git.changed

- name: Make install
  command: make install
  args:
    chdir: "{{ ansible_env.HOME }}/.cache/adapta-gtk-theme"
  register: adapta_theme_make_install
  become: true
  become_user: "{{ ansible_env.USER }}"
  when: adapta_gtk_theme_git.changed

- name: Set adapta-gtk-theme
  command: "{{ item }}"
  with_items:
    - "gsettings set org.gnome.desktop.interface gtk-theme Adapta"
    - "gsettings set org.gnome.desktop.wm.preferences theme Adapta"
  become: false
  when: adapta_gtk_theme_git.changed

- name: Set Windows Manager Theme
  command: "gsettings set org.gnome.desktop.wm.preferences theme Adapta"

